### ISSUE TITLE
issues with dnd5e 1.1.0 due to the movement change ?

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/R20Converter#60]
dnd5e should auto migrate it but it doesn't look like it does.

**Comment by Someone2345** [comment]
Seems like only "walk" speed comes across, no other references (fly, swim etc).
(this is after the actors update in the world, or after the compendium update command is run).

**Comment by kakaroto** [comment]
I'm not sure why the dnd5e migration of the data fails, but it should be fixed now with the 0.10.0 release of R20Converter which uses the new format.
