### ISSUE TITLE
Make sure scene dimensions are always integers

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/R20Converter#63]
To avoid issues with foundry that does a new validation of integer fields

**Comment by tgm4883** [comment]
I believe this is an issue with maps I imported into r20 and stretched. Foundry happily accepts the world with scenes with non-integer fields but won't let me actually fix them inside foundry. If R20Converter could at least round that to an integer then I think I could check and adjust the imported files.

**Comment by kakaroto** [comment]
Yeah the issue is that if a scene has a non integer value, Foundry doesn't let you fix it.
Either way, it's fixed in the next update now 👍
