### ISSUE TITLE
My players/monsters/enemies not being imported into Foundry

### ISSUE THREAD

**Issue by phil-the-dev** [kakaroto/R20Converter#72]
I've tried doing this twice and I don't know what I'm possibly doing wrong. I'm exporting my Roll20 campaign as a world, which is pretty much just LMoP, 2 compendiums, and my players and yet I don't seem to retain anything that's not an image. I can see all of the tokens and images, and the exporter showed that my player characters and enemies were exported, but when I upload them to The Forge, it seems to leave their character sheets behind. Any idea what I'm doing wrong?

**Comment by phil-the-dev** [comment]
Nevermind, just a dummy, didn't realize I imported originally as a compendium. Second import was as a world, but I kept visiting the old compendium version. closing! Thanks for making this app, though!

**Comment by kakaroto** [comment]
Glad you figured it out, wasn't sure how to answer :D
