### ISSUE TITLE
Problems converting certain R20 modules

### ISSUE THREAD

**Issue by Valle1505** [kakaroto/R20Converter#82]
I just bought out of the abyss on roll20 with the intension of converting it with the r20converter and using it in foundry, but several of the maps doesn't get converted correct. I have tried with both zip and json files to same effect. I have used the converter before with success for both the ToA and CoS modules.

**Comment by kakaroto** [comment]
Hi,
could you be more specific on what you mean by "the maps don't get converted correctly", that's extremely vague and doesn't give me any information to help you resolve whatever issue you're having.
Explain in detail what is expected and what you actually get, show screenshots of both the roll20 map and the foundry map to pinpoint differences you see, etc..
I can't help without more info.
Thanks.

**Comment by Valle1505** [comment]
It was a bit weird, but it seems it was connected on my memory running low at the time, which resulted in certain maps not showing… So you can consider it fixed.

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Youness ***@***.***>
Sendt: 22. august 2022 18:40
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [kakaroto/R20Converter] Problems converting certain R20 modules (Issue #82)


Hi,
could you be more specific on what you mean by "the maps don't get converted correctly", that's extremely vague and doesn't give me any information to help you resolve whatever issue you're having.
Explain in detail what is expected and what you actually get, show screenshots of both the roll20 map and the foundry map to pinpoint differences you see, etc..
I can't help without more info.
Thanks.

**Comment by kakaroto** [comment]
> It was a bit weird, but it seems it was connected on my memory running low at the time, which resulted in certain maps not showing… So you can consider it fixed.

Ah I see, that makes sense, if Foundry itself was crashing/failing to display the scene, then it would appear like the scene wasn't converted at all.
Thanks!
