### ISSUE TITLE
I have pre-purchase questions - how may I ask them?

### ISSUE THREAD

**Issue by iLLHunter** [kakaroto/R20Converter#87]
I can find no socials, besides Patreon, where you charge people to even comment or speak. You're named after a restaurant, making google searches for ways to contact you harder. Is there a discord where we can go to for support or ask questions? X/twitter DM? Bluesky? I would prefer not making a development issue on github, but it seems like the only option, so here we are.

After reading material/description I have some questions. I would like to purchase content on roll20 and have it for use in Foundry, especially Feats, but those are not mentioned specifically and I need to be able to get those imported. I don't want to manually create them all. 

The description talks about importing Campaigns, but will those be able to import all the spells/cantrips, monsters, abilities, etc etc? 

I'm looking to create full compendiums inside Foundry where all the content that might be needed, has already been imported in.

Your patreon 'Player' tier mentions we get everything from 'NPC' tier, but NPC tier does not exist, so we don't know what that player tier provides. Does it provide full access to the tool?

Respectfully,
iLL

**Comment by kakaroto** [comment]
Hi iLL!
Interesting, I hadn't realized that a link to my discord server was not visible unless someone already subscribed to my Patreon.
Here's the invite to my discord server: https://discord.gg/N6BNn3x
Also, I don't know about the "you're named after a restaurant" 🤣 I had never seen that one before. I'm actually named after an anime character. 
To answer your questions, feats, spells, etc... are all getting converted, you can see the conversion process here: https://www.youtube.com/watch?v=xAPS6NXZ0uM

I've updated my patreon bio to add a link to the discord server, as well as changed the Player tier to not refer to the old archived tier (thanks for catching that!).

All that being said. I do plan on open-sourcing R20Converter and releasing it for free soon. I'm not done with that process, but I don't mind just sharing the app here until I can actually finish open sourcing it.

Here's download links for R20Converter, so you don't have to purchase it at this time: 
- Linux: https://www.dropbox.com/scl/fi/l713l31uyhdtt117hwzq4/R20Converter-0.13.3-win64.zip?rlkey=bt7xvluni3ymtlk7jzvs3o3g5&dl=0
- Windows: https://www.dropbox.com/scl/fi/l713l31uyhdtt117hwzq4/R20Converter-0.13.3-win64.zip?rlkey=bt7xvluni3ymtlk7jzvs3o3g5&dl=0
- Mac: https://www.dropbox.com/s/co7bzkp71bzvjhp/R20Converter-0.13.3.1.dmg?dl=0

Enjoy!
