### ISSUE TITLE
R20Converter just doesn't work(?)

### ISSUE THREAD

**Issue by SQLdefaulterror** [kakaroto/R20Converter#90]
Hi, it's just as the title says. When I try to start R20Converter, I get a screen like this just as I double-click the app:
![r20converter_screenshot](https://github.com/user-attachments/assets/1d92bfd2-3579-44e0-8ce8-5e4444f33a5e)

The version I have own is R20Converter-0.12.2-win64 and it worked just fine like a month ago.

**Comment by kakaroto** [comment]
It sounds like something is wrong with your installation of it, obviously, it's not supposed to behave that way and something broke it between last month and now (did you delete some files from it or something?)
Either way, it's not the latest release, 0.12.2 is from May 2023.
Get the latest version (now available for free), you'll have better results with it anyway: https://www.patreon.com/posts/r20converter-0-x-88293565

**Comment by SQLdefaulterror** [comment]
Thank you!! You're great man!
